server: 
  port: 8080
  undertow:
    worker-threads: 32
        
spring: 
  application:
    name: gateway
  cloud:
    gateway: 
      default-filters:
      - name: ipLimit
    
logging:
  path: /tmp/log/
  file: gateway.log
