server: 
  port: 8080
  undertow:
    worker-threads: 32
        
spring: 
  application:
    name: gateway
  cloud:
    gateway: 
      default-filters:
      - name: ipLimit
  data:
    mongodb:
      host: localhost
      port: 27017
      database: logDB
    
logging:
  path: /tmp/log/
  file: gateway.log
