server: 
  port: 8080
  undertow:
    worker-threads: 32
        
spring: 
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    gateway: 
      routes:
      - id: my-test
        uri: http://123
        predicates:
        - Path=*
        filters: 
        - name: RequestRateLimiter
          args: 
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 20
            key-resolver: "#{@userLimit}"
  application:
    name: gateway
    
logging:
  path: /tmp/log/
  file: gateway.log

  